version: '3.9'

services:
  z-connect:
    image:  kashiiitech/zconnect-web 
    container_name: z-connect-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped